# 로그
logging:
  level:
    root: info


# H2
spring:
  h2:
    console:
      enabled: true
      path: /h2

# Datasource
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: sa
    password:

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

